//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryWebapp.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string Id { get; set; }
        public string TransactionNumber { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string CustomerId { get; set; }
        public string PaymentId { get; set; }
        public string ItemId { get; set; }
        public int DiscountPrice { get; set; }
        public decimal Weight { get; set; }
        public int Price { get; set; }
        public System.DateTime EstimationClear { get; set; }
        public string Status { get; set; }
        public string PaymentStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual MasterCustomer MasterCustomer { get; set; }
        public virtual MasterPayment MasterPayment { get; set; }
        public virtual MasterItem MasterItem { get; set; }
    }
}
